### ISSUE TITLE
GDBus.Error

### ISSUE THREAD

**Issue by liko28s** [PedroHLC/osdlyrics#32]
Hi guys!, when I'm trying to start the app this message is prompted in the console:

*Error*: in function _start_daemon_cb: ol_main.c[761]
Unable to start daemon: GDBus.Error:org.freedesktop.DBus.Error.Spawn.ChildExited: Process org.osdlyrics.Daemon exited with status 1

I've installed the Development Dbus and Libdbus packages and still no luck.

Any idea?

**Comment by PedroHLC** [comment]
Which version of osdlyrics are you running, when and by whom was it compiled? Which system/distro? Which processor architecture?

**Comment by liko28s** [comment]
Hi, i'm running Kubuntu 15.04 in an x86-64, while compiling no errors found

**Comment by PedroHLC** [comment]
You're error says OSDLyrics wasn't able to keep DBUS Connection - but I can be wrong, DBUS may have changed it API. But before taking any action, can you test your dbus?
You can see first, if there is at least one dbus-daemon running with  "--session" parameter, you can do this using this:
ps -ef | grep dbus | grep -v grep

**Comment by liko28s** [comment]
This is the output of `ps -ef | grep dbus | grep -v grep`
```
ps -ef | grep dbus | grep -v grep
message+   613     1  0 02:45 ?        00:00:04 /usr/bin/dbus-daemon --system --address=systemd: --nofork --nopidfile --systemd-activation
root       625     1  0 02:45 ?        00:00:01 /usr/sbin/thermald --no-daemon --dbus-enable
gdm       1272  1243  0 02:45 tty7     00:00:00 dbus-daemon --print-address 4 --session
gdm       1283  1278  0 02:45 tty7     00:00:00 /usr/bin/dbus-daemon --config-file=/etc/at-spi2/accessibility.conf --nofork --print-address 3
lp        1850  1847  0 03:03 ?        00:00:00 /usr/lib/cups/notifier/dbus dbus:// 
nobody    2284   640  0 07:29 ?        00:00:11 /usr/sbin/dnsmasq --no-resolv --keep-in-foreground --no-hosts --bind-interfaces --pid-file=/run/sendsigs.omit.d/network-manager.dnsmasq.pid --listen-address=127.0.1.1 --conf-file=/var/run/NetworkManager/dnsmasq.conf --cache-size=0 --proxy-dnssec --enable-dbus=org.freedesktop.NetworkManager.dnsmasq --conf-dir=/etc/NetworkManager/dnsmasq.d
ramialv   2481  2403  0 07:29 tty2     00:00:14 dbus-daemon --print-address 4 --session
root     11641     1  0 12:23 ?        00:00:00 dbus-launch --autolaunch 282f34fa940c4805add10b5c343ec13c --binary-syntax --close-stderr
root     11642     1  0 12:23 ?        00:00:00 /usr/bin/dbus-daemon --fork --print-pid 5 --print-address 7 --session
```

**Comment by PedroHLC** [comment]
Ok, your user's daemon seems to be running. Can you get me your dbus-daemon "--version", as well as the version of all yours dbus* packages? Have you tried others osdlyrics versions? What about compiling one legacy version? Are you having any other problem related do dbus?

**Comment by liko28s** [comment]
Hi, I'm running `1.10.0` all the other packages are updated, other applications seems to work fine.
Yes, I'm trying with another versions, even with the .deb available in the original repo and no luck.

**Comment by PedroHLC** [comment]
I need to follow the code path until the error, can you send the entire output of "osdlyrics -d info" ?

**Comment by lenoch** [comment]
@liko28s, does your Kubuntu run under systemd already by any chance? I suppose so. Please post the relevant parts of the session log. The important part of osdlyrics' backend (written in Python) must have encountered an error, and you should be able to find the details (an exception “traceback”) in the output of this command:

journalctl --user -b

**Comment by liko28s** [comment]
Of course:
```
$osdlyrics -d info
*Debug*: in function _client_name_acquired_cb: ol_main.c[635]
Client bus name acquired
*Debug*: in function _name_vanished_cb: ol_main.c[720]
Daemon lost, try to activate it
*Debug*: in function _name_vanished_cb: ol_main.c[733]
Daemon appeared
*Error*: in function _start_daemon_cb: ol_main.c[761]
Unable to start daemon: GDBus.Error:org.freedesktop.DBus.Error.Spawn.ChildExited: Process org.osdlyrics.Daemon exited with status 1

```
it's all

**Comment by lenoch** [comment]
@liko28s, can you also post the output of journalctl --user -b ?

**Comment by liko28s** [comment]
Hi, if i run `journalctl --user -b `
```
No journal files were found.
-- No entries --
```
The same response is printed without `-b`

**Comment by lenoch** [comment]
OK, so let's look at osdlyrics' daemon directly.

Can you run /usr/bin/python2 /usr/lib/osdlyrics/daemon/main.py and post the traceback it writes to the console?

**Comment by liko28s** [comment]
Hi, when i'm running
`python /usr/local/lib/osdlyrics/daemon/main.py`
get the response
```
Traceback (most recent call last):
  File "/usr/local/lib/osdlyrics/daemon/main.py", line 28, in <module>
    from osdlyrics.metadata import Metadata
  File "/usr/local/lib/python2.7/dist-packages/osdlyrics/metadata.py", line 26, in <module>
    from . import utils
  File "/usr/local/lib/python2.7/dist-packages/osdlyrics/utils.py", line 29, in <module>
    import pycurl
```
Then I've installed the package pycurl `apt-get install python-pycurl`
Now it works correctly , however I do not have the icon in the system tray to make adjustments , but that is a separate problem .
Thank you

**Comment by lenoch** [comment]
I use stalonetray to display icons.
