### ISSUE TITLE
New branch for serial port output

### ISSUE THREAD

**Issue by thestumbler** [PedroHLC/osdlyrics#33]
I'm plan to make a modification to osdlyrics to send the song lyrics over the serial port.  The purpose being to display the lyrics text on an external monitor using an external HDMI overlay box.  I control the firmware in this overlay box, and I will write the proposed patch.  So naturally I could invent a suitable protocol.  However, I wonder if any similar protocol already exists.

I could, I suppose, physically send the actual LRC file format string to the box every line in sync with the music.  In that case, the time information of the line wouldn't be important, however if there were word/phrase time tags, they would have to be adjusted to reference the start of the line.  Are there any standard or semi-standard interfaces?

Note that I say "serial port", but it can just as well be implemented over a virtual USB serial port, too (my box has both). In fact, my box has both interfaces, the USB port is slightly more convenient to use, and is indeed being used as a virtual serial port for similar applications already.

**Comment by lenoch** [comment]
I am not sure what you are after; but if you wanted to wrap the individual lyrics lines (or even parts of them, see an example of the extended LRC format https://github.com/PedroHLC/osdlyrics/blob/master/ROADMAP.md#nice-things-to-have) you could also treat them as you would film subtitles.

The “protocol” would then be a multimedia container capable of streaming. I was hoping to look into Matroska some day but I don’t think in-band subtitles are in their best form yet; but Matroska-derived WebM seems to have proven the format is probably well-suited for streaming. I guess I can’t help you much here unless I understand better your idea.

You are probably best off inventing your own protocol for now; and if you find a well-established protocol later, the two will probably look similar so the switch won’t be hard.

**Comment by PedroHLC** [comment]
There is nothing here to us for implement or fix. One can modify this project to display synced lyrics to through GTK (default behavior) and/or any other place that lives inside the limits of python itself: "ol_{scroll,osd}_module.c" for example handles the interaction between the display and music time, one can notice that it receives the lyrics through "set_lrc" and the exactly time through "set_played_time". The OSD widget might be better for one to implement in a small LCD screen (like those for Arduino) as it interact by lines and not 2D positioning.
