### ISSUE TITLE
Can I install it on Archlinux?

### ISSUE THREAD

**Issue by onrea** [PedroHLC/osdlyrics#37]
Is there any pkgbuild/aur to install it on Archlinux?!

**Comment by lenoch** [comment]
You can give https://aur.archlinux.org/packages/osdlyrics-git/ a try.

If you don't see a notification icon, either install stalonetray or run 'configure' with --enable-appindicator=yes and report back if it helped (I haven't done so yet and I am curious).

Or if you run into other issues, be sure to let us know! :-)

**Comment by PedroHLC** [comment]
this repo is used in https://aur.archlinux.org/packages/osdlyrics-git/
I'm also still maintaining https://aur.archlinux.org/packages/osdlyrics-pedrohlc/ that uses legacy-dev branch, but this version won't receive updates and it's here just if your player isn't supported by the newer version.

**Comment by lenoch** [comment]
On AppIndicator:

`configure --enable-appindicator=yes` needs `libappindicator-gtk2` from AUR, which is a split package providing also `libappindicator-gtk3` and `libappindicator-sharp` so it pulls in quite a lot of makedepends.

I managed to build osdlyrics successfully but found out that my Enlightenment from Git currently lacks a systray so I couldn't see the icon natively. stalonetray displayed it but it was oversized by default, I would probably have to force a smaller size somehow. I am happy with XEmbed so now.
