### ISSUE TITLE
can you add install instruction in readme?

### ISSUE THREAD

**Issue by cosven** [PedroHLC/osdlyrics#38]
Is this project still in development, can you add install instruction in readme?

**Comment by PedroHLC** [comment]
Will be added, by now, consider this a "how to install":
```
./autogen.sh
./configure --prefix=/usr PYTHON=/usr/bin/python2
make
make install
```

**Comment by TilyTao** [comment]
tily@Tily:~/下载/osdlyrics-master$ osdlyrics
*Error*: in function _start_daemon_cb: ol_main.c[761]
Unable to start daemon: GDBus.Error:org.freedesktop.DBus.Error.Spawn.ChildExited: Process org.osdlyrics.Daemon exited with status 1

**Comment by ItachiUchiha91** [comment]
Same error here.

**Comment by PedroHLC** [comment]
Thanks, within @osdlyrics/osdlyrics there will be a wiki article "How to compile & install", stay tuned.
